#!/bin/sh

# ponyguests — Login wrapper to enable guest accounts
# 
# Copyright © 2014  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e


# The username
username="${1}"
# Supplemental groups
groups="games network guests"
# Additional supplemental groups that are added
# if the guest logs in via the TTY
tty_groups="lp uucp lock video audio scanner"

# A random password
password="$(cat /proc/sys/kernel/random/uuid)"


# Check whether the guests is logging in via the TTY
tty="$(tty 2>/dev/null || echo not a tty)"
if echo "${tty}" | grep -Po '^/dev/tty[0-9]+$' 2>/dev/null; then
    groups="${tty_groups} ${groups}"
fi

# Get list of supplemental groups for `useradd`
supplemental_groups=
G=-G
for group in $groups ; do
    if getent group $group >/dev/null 2>/dev/null; then
	supplemental_groups=$supplemental_groups,$group
    fi
done
if [ "${supplemental_groups}" = "" ]; then
    G=
else
    supplemental_groups=${supplemental_groups:1}
fi


# Create guest account
useradd -c "Guest account" \
	-d "/tmp/ponyquests/home/$(username)" \
	$G $supplemental_groups \
	-m -U \
	-p "${password}" \
	"$(username)"

